apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eb362mj5u-nodejs
  janus-idp.io/tekton: eb362mj5u-nodejs
  backstage.io/kubernetes-id: eb362mj5u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eb362mj5u-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
